// Generated by CoffeeScript 1.12.5
var gulp, rename, sass, watch;

gulp = require('gulp');

rename = require('gulp-rename');

watch = require('gulp-watch');

sass = require('gulp-sass');

gulp.task('default', function() {
  return watch('app/public/css/**/*.sass', function() {
    return gulp.src('app/public/css/**/*.sass').pipe(sass().on('error', sass.logError)).pipe(gulp.dest('app/public/css'));
  });
});
