// Generated by CoffeeScript 1.12.5
var Eureca, app, boxen, center, eurecaServer, express, favicon, figlet, game, i, out, port, server, term, termkit;

termkit = require('terminal-kit');

term = termkit.terminal;

figlet = require('figlet');

center = require('center-align');

boxen = require('boxen');

require('colors');

out = {
  info: function(phrase) {
    term.bold.magenta('⬢')(' ').bold(phrase)('\n');
    return out.cliRebase();
  },
  error: function(phrase) {
    term.bold.red('λ')(' ').bold(phrase)('\n');
    return out.cliRebase();
  },
  promo: function(phrase) {
    var text;
    text = figlet.textSync(phrase, {
      font: 'Big',
      horizontalLayout: 'default',
      verticalLayout: 'default'
    });
    term.bold.brightCyan(text)('\n');
    return out.cliRebase();
  },
  welcome: function(phrase) {
    term.bold.underline.brightCyan(phrase)('\n');
    return out.cliRebase();
  },
  message: function(phrase) {
    term('\n');
    term.bold(boxen(center(phrase + ""), {
      padding: 1
    }));
    return term('\n\n');
  },
  text: function(phrase) {
    var j, len, lines, ref, result, results, string;
    lines = phrase.split(/\n/gi).length;
    if (lines === 1) {
      return term.bold("→ ").bold(phrase)("\n");
    } else {
      term.bold("→ ")("\n");
      result = [];
      ref = phrase.split(/\n/gi);
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        string = ref[j];
        term.bold("  " + string);
        results.push(term('\n'));
      }
      return results;
    }
  },
  help: function() {
    return out.text(['help'.cyan + '  - display this help', 'admin'.cyan + ' - register player "admin"', 'exit'.cyan + '  - stop server and exit from server\'s cli'].join('\n'));
  },
  cli: function() {
    var f;
    f = function() {
      return out.cliLine = term.inputField(function(err, input) {
        var com;
        if (err) {
          console.dir(err);
          return;
        }
        term('\n');
        com = 0;
        if (input.match(/^help/i)) {
          out.help();
          com++;
        }
        if (input.match(/^exit/i)) {
          process.exit();
          com++;
        }
        if (!com) {
          setImmediate(function() {
            return out.error('Unknown command!');
          });
        }
        return f();
      });
    };
    return f();
  },
  cliRebase: function() {
    if (out.cliLine) {
      return out.cliLine.rebase();
    }
  }
};

express = require('express');

favicon = require('serve-favicon');

app = express(app);

app.engine('html', require('ejs').renderFile);

app.set('view engine', 'html');

app.use(express["static"](__dirname + "/public"));

app.set('views', __dirname + '/views');

server = require('http').createServer(app);

Eureca = require('eureca.io');

eurecaServer = new Eureca.Server({
  allow: ['playerUpdated', 'playerRemoved']
});

eurecaServer.attach(server);

i = 0;

app.get('/', function(req, res, next) {
  return res.render('index.html');
});

port = process.env.PORT || 5000;

server.listen(port);

out.promo('SHOOTER.IO');

out.welcome('Welcome in SHOOTER.IO server!');

out.message('Listening on ' + ('http://localhost:' + port).blue + '!');

out.welcome('Type "help" for view list of avaliable commands.');

out.cli();

game = require('./scripts/main.js')(eurecaServer, out);
