// Generated by CoffeeScript 1.12.5
var Eureca, app, eurecaServer, express, favicon, game, i, server;

express = require('express');

favicon = require('serve-favicon');

app = express(app);

app.engine('html', require('ejs').renderFile);

app.set('view engine', 'html');

app.use(express["static"](__dirname + "/public"));

app.set('views', __dirname + '/views');

server = require('http').createServer(app);

Eureca = require('eureca.io');

eurecaServer = new Eureca.Server({
  allow: ['playerUpdated', 'playerRemoved']
});

eurecaServer.attach(server);

i = 0;

app.get('/', function(req, res, next) {
  return res.render('index.html');
});

server.listen(process.env.PORT || 5000);

game = require('./scripts/main.js')(eurecaServer);
